// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-O8nPQKAB98f2_3CoFcCORxiXuHuZm8',
    appId: '1:819851365497:web:37390b9445e168e26498a8',
    messagingSenderId: '819851365497',
    projectId: 'fir-flutter-codelab-ed094',
    authDomain: 'fir-flutter-codelab-ed094.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ed094.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAey8MqeXOKZI71Bf0wPimkWGj5bO1ZgZk',
    appId: '1:819851365497:android:bd34b39ef2b9d4a46498a8',
    messagingSenderId: '819851365497',
    projectId: 'fir-flutter-codelab-ed094',
    storageBucket: 'fir-flutter-codelab-ed094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKUfsQ26D4HoF0B1x76yJXHLunHBH8Pg',
    appId: '1:819851365497:ios:6634b13988233b546498a8',
    messagingSenderId: '819851365497',
    projectId: 'fir-flutter-codelab-ed094',
    storageBucket: 'fir-flutter-codelab-ed094.appspot.com',
    iosClientId: '819851365497-ihq2st4nau25170nbha0f5jfsrpmrf8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKUfsQ26D4HoF0B1x76yJXHLunHBH8Pg',
    appId: '1:819851365497:ios:6634b13988233b546498a8',
    messagingSenderId: '819851365497',
    projectId: 'fir-flutter-codelab-ed094',
    storageBucket: 'fir-flutter-codelab-ed094.appspot.com',
    iosClientId: '819851365497-ihq2st4nau25170nbha0f5jfsrpmrf8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
